#!/usr/bin/env node
/**
 * Bundle the two runtime entry points into self-contained, dependency-free ESM
 * files under dist/.
 *
 * WHY: Claude Code installs a marketplace plugin by cloning the repo — it does
 * NOT run `npm install`, so the installed plugin has no node_modules and a
 * `node src/index.js` MCP server would fail with ERR_MODULE_NOT_FOUND. (NODE_PATH
 * does not help either: ESM import ignores it.) Bundling inlines every dependency
 * so the plugin runs from a bare clone with zero runtime deps — no npm, no
 * network, no first-run hook.
 *
 * The committed dist/ bundles are what `.claude-plugin/plugin.json` points at.
 * CI rebuilds and fails if dist/ is stale (see .github/workflows/ci.yml).
 */
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));

const entries = [
  { in: 'src/index.js', out: 'dist/index.mjs' },   // in-process MCP channel plugin (plugin.json target)
  { in: 'src/bridge.js', out: 'dist/bridge.mjs' }, // split-topology resident bridge
];

for (const e of entries) {
  await build({
    absWorkingDir: root,
    entryPoints: [e.in],
    outfile: e.out,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    sourcemap: false,
    minify: false, // keep the shipped bundle auditable; source is in the repo too
    logLevel: 'info',
    banner: { js: '// AUTO-GENERATED by scripts/build.js — do not edit. Source: src/. Rebuild: npm run build.' },
  });
  console.log(`bundled ${e.in} -> ${e.out}`);
}
